import pandas_datareader.data as web
import datetime as dt
import numpy as np
import yfinance as yf
import opstrat as op
import yfinance as yf
import pandas as pd
import numpy as np

tickers = ['AAPL',
    'MSFT',
    'AMZN',
    'TSLA',
    'GOOGL',
    'GOOG',
    'BRK-B',
    'UNH',
    'JNJ',
    'XOM',
    'JPM',
    'META',
    'PG',
    'NVDA',
    'V',
    'CVX',
    'HD',
    'MA',
    'PFE',
    'ABBV',
    'BAC',
    'LLY',
    'KO',
    'PEP',
    'COST',
    'MRK',
    'TMO',
    'AVGO',
    'DIS',
    'MCD',
    'WMT',
    'ABT',
    'DHR',
    'CSCO',
    'ACN',
    'VZ',
    'NEE',
    'WFC',
    'CRM',
    'BMY',
    'CMCSA',
    'TXN',
    'COP',
    'ADBE',
    'PM',
    'LIN',
    'QCOM',
    'UNP',
    'UPS',
    'NKE',
    'CVS',
    'RTX',
    'LOW',
    'AMD',
    'MS',
    'AMGN',
    'MDT',
    'SPGI',
    'HON',
    'T',
    'INTU',
    'INTC',
    'ELV',
    'GS',
    'AMT',
    'IBM',
    'PYPL',
    'ORCL',
    'SCHW',
    'SBUX',
    'NFLX',
    'DE',
    'LMT',
    'CAT',
    'ADP',
    'AXP',
    'C',
    'CI',
    'BLK',
    'NOW',
    'PLD',
    'BA',
    'TMUS',
    'MDLZ',
    'DUK',
    'SO',
    'CB',
    'GILD',
    'BKNG',
    'MMC',
    'AMAT',
    'ADI',
    'MO',
    'TGT',
    'REGN',
    'TJX',
    'SYK',
    'GE',
    'ISRG',
    'ZTS',
    'PGR',
    'VRTX',
    'BDX',
    'EOG',
    'NOC',
    'CCI',
    'CME',
    'PNC',
    'CSX',
    'WM',
    'D',
    'MMM',
    'TFC',
    'CL',
    'HUM',
    'USB',
    'FISV',
    'BSX',
    'ATVI',
    'AON',
    'GM',
    'EW',
    'MU',
    'F',
    'OXY',
    'LRCX',
    'NSC',
    'EL',
    'EQIX',
    'SLB',
    'ETN',
    'ITW',
    'APD',
    'DG',
    'PXD',
    'ICE',
    'SRE',
    'SHW',
    'GD',
    'FIS',
    'MPC',
    'AEP',
    'KLAC',
    'CNC',
    'MCK',
    'FDX',
    'SNPS',
    'ADM',
    'PSA',
    'EMR',
    'CMG',
    'HCA',
    'MRNA',
    'MCO',
    'MET',
    'ORLY',
    'GIS',
    'CTVA',
    'CDNS',
    'MAR',
    'LHX',
    'ADSK',
    'CHTR',
    'FCX',
    'APH',
    'AIG',
    'VLO',
    'DVN',
    'AZO',
    'NXPI',
    'EXC',
    'ENPH',
    'ROP',
    'KMB',
    'TEL',
    'COF',
    'SYY',
    'MSI',
    'A',
    'ECL',
    'XEL',
    'WMB',
    'TRV',
    'IQV',
    'PSX',
    'STZ',
    'JCI',
    'AJG',
    'O',
    'PAYX',
    'HLT',
    'GPN',
    'TT',
    'MSCI',
    'DXCM',
    'MCHP',
    'AFL',
    'KMI',
    'ALL',
    'CTAS',
    'EA',
    'PRU',
    'HES',
    'DOW',
    'CARR',
    'ED',
    'PH',
    'FTNT',
    'NEM',
    'SBAC',
    'PEG',
    'ALB',
    'MTB',
    'YUM',
    'WELL',
    'RMD',
    'BK',
    'MNST',
    'SPG',
    'CTSH',
    'VICI',
    'HSY',
    'ROST',
    'WEC',
    'DLR',
    'ILMN',
    'KR',
    'NUE',
    'DLTR',
    'TDG',
    'AMP',
    'RSG',
    'KEYS',
    'BIIB',
    'CMI',
    'ES',
    'BAX',
    'ON',
    'IDXX',
    'PCAR',
    'VRSK',
    'OTIS',
    'WBD',
    'MTD',
    'PPG',
    'HPQ',
    'DFS',
    'DD',
    'ROK',
    'CEG',
    'AVB',
    'AME',
    'OKE',
    'KDP',
    'FAST',
    'IFF',
    'AWK',
    'HAL',
    'FRC',
    'ANET',
    'APTV',
    'STT',
    'EIX',
    'TROW',
    'DTE',
    'CTRA',
    'EXR',
    'IT',
    'GLW',
    'EQR',
    'WBA',
    'KHC',
    'FITB',
    'ZBH',
    'ODFL',
    'EBAY',
    'CPRT',
    'ETR',
    'WY',
    'AEE',
    'EPAM',
    'GWW',
    'WTW',
    'FE',
    'CDW',
    'FTV',
    'FANG',
    'BKR',
    'EFX',
    'DHI',
    'ARE',
    'ULTA',
    'SIVB',
    'GPC',
    'HIG',
    'LUV',
    'PPL',
    'VMC',
    'TSCO',
    'RF',
    'NDAQ',
    'DAL',
    'TSN',
    'CF',
    'ABC',
    'RJF',
    'MLM',
    'ANSS',
    'LH',
    'URI',
    'LYB',
    'HBAN',
    'TTWO',
    'CNP',
    'WST',
    'MOH',
    'STE',
    'IR',
    'MOS',
    'NTRS',
    'PWR',
    'MKC',
    'LEN',
    'CMS',
    'MAA',
    'MRO',
    'BR',
    'VTR',
    'BALL',
    'CHD',
    'CFG',
    'CAH',
    'ALGN',
    'PFG',
    'MPWR',
    'WAT',
    'AMCR',
    'K',
    'AES',
    'DOV',
    'SEDG',
    'TDY',
    'CLX',
    'HOLX',
    'HPE',
    'VRSN',
    'XYL',
    'ESS',
    'FDS',
    'DRI',
    'PAYC',
    'KEY',
    'PKI',
    'WAB',
    'SWKS',
    'EXPD',
    'SYF',
    'MTCH',
    'EXPE',
    'CAG',
    'CTLT',
    'FLT',
    'ATO',
    'ZBRA',
    'IEX',
    'J',
    'IRM',
    'NTAP',
    'EVRG',
    'SJM',
    'LNT',
    'CINF',
    'TRMB',
    'AVY',
    'DGX',
    'TYL',
    'IP',
    'COO',
    'BBY',
    'JBHT',
    'OMC',
    'AKAM',
    'BRO',
    'ETSY',
    'WRB',
    'JKHY',
    'CHRW',
    'TXT',
    'APA',
    'PARA',
    'KMX',
    'PEAK',
    'CPT',
    'FMC',
    'LVS',
    'UDR',
    'TER',
    'LKQ',
    'POOL',
    'GNRC',
    'VFC',
    'GRMN',
    'HWM',
    'SWK',
    'HRL',
    'LDOS',
    'INCY',
    'DPZ',
    'HST',
    'BF-B',
    'KIM',
    'CBOE',
    'PKG',
    'STX',
    'UAL',
    'LYV',
    'NVR',
    'TECH',
    'MGM',
    'PTC',
    'NDSN',
    'WDC',
    'NI',
    'MAS',
    'BXP',
    'CE',
    'SNA',
    'VTRS',
    'RCL',
    'RE',
    'LW',
    'SBNY',
    'FOXA',
    'NRG',
    'IPG',
    'L',
    'TFX',
    'CCL',
    'CMA',
    'EMN',
    'AAP',
    'WRK',
    'CRL',
    'BIO',
    'HSIC',
    'HAS',
    'CZR',
    'MKTX',
    'TAP',
    'CPB',
    'GL',
    'HII',
    'QRVO',
    'PHM',
    'AAL',
    'JNPR',
    'FFIV',
    'ZION',
    'BBWI',
    'REG',
    'BWA',
    'AIZ',
    'TPR',
    'RHI',
    'LNC',
    'PNW',
    'ALLE',
    'LUMN',
    'WHR',
    'CDAY',
    'ROL',
    'SEE',
    'OGN',
    'PNR',
    'XRAY',
    'AOS',
    'FRT',
    'WYNN',
    'DXC',
    'NWSA',
    'BEN',
    'UHS',
    'NCLH',
    'NWL',
    'ALK',
    'DVA',
    'IVZ',
    'MHK',
    'PENN',
    'FOX',
    'RL',
    'DISH',
    'VNO',
    'PVH',
    'NWS',
    'EMBC'
]

## Risk Free Rate
input = "^TNX"
output = yf.Ticker(input)
latest_price2 = output.history(period='1d')['Close'][0]
rate = round(latest_price2, 2)

def get_beta(stock_symbol, market_index_symbol):
    stock_data = yf.Ticker(stock_symbol).history(period='max')
    market_index_data = yf.Ticker(market_index_symbol).history(period='max')

    # Get the overlapping dates in the historical data
    start_date = max(stock_data.index.min(), market_index_data.index.min())
    end_date = min(stock_data.index.max(), market_index_data.index.max())

    # Slice the historical data to only include the overlapping dates
    stock_data = stock_data.loc[start_date:end_date]
    market_index_data = market_index_data.loc[start_date:end_date]

    # Calculate the daily returns for the stock and market index
    stock_returns = stock_data['Close'].pct_change()[1:]
    market_returns = market_index_data['Close'].pct_change()[1:]

    # Calculate the beta using the covariance and volatility of the returns
    covariance = stock_returns.cov(market_returns)
    market_volatility = market_returns.var()
    return covariance / market_volatility

def get_cheapest_straddles(tickers):
    cheapest_straddles = {}
    T = 90
    for ticker in tickers:
        beta = get_beta(ticker, 'SPY')
        stock = yf.Ticker(ticker)
        latest_price = stock.history(period='1d')['Close'][0]
        price = round(latest_price, 2)
        output2 = yf.Ticker('^VIX',)
        latest_price3 = output2.history(period='1d')['Close'][0]
        vol = round(latest_price3, 2)
        St = price
        K = price
        r = rate
        v= (vol*beta)
        call=op.black_scholes(K=K, St=St, r=r, t=T, v=v, type='c')
        put=op.black_scholes(K=K, St=St, r=r, t=T, v=v, type='p')
        strategy_cost = (call['value']['option value']) + (put['value']['option value'])
        cheapest_straddles[ticker] = strategy_cost
    return sorted(cheapest_straddles.items(), key=lambda x: x[1])

if __name__ == '__main__':
    cheapest_straddles = get_cheapest_straddles(tickers)
    for ticker, strategy_cost in cheapest_straddles:
        print(f'{ticker} - cheapest straddle cost: {strategy_cost:.2f}')
